modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="shitposting_colombian"
version="1.0.0"
displayName="Shitposting colombian"
credits="Ferxas"
displayURL="https://allmylinks.com/ferxas"
authors="Ferxas"

[[dependencies.shitposting_colombian]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



